//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigFile.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal MunicipalCodeLengthMax {
            get {
                return ((decimal)(this["MunicipalCodeLengthMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal MunicipalCodeLengthMin {
            get {
                return ((decimal)(this["MunicipalCodeLengthMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal BranchOfficeLengthMax {
            get {
                return ((decimal)(this["BranchOfficeLengthMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal BranchOfficeLengthMin {
            get {
                return ((decimal)(this["BranchOfficeLengthMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public decimal SealRegistrationLengthMax {
            get {
                return ((decimal)(this["SealRegistrationLengthMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal SealRegistrationLengthMin {
            get {
                return ((decimal)(this["SealRegistrationLengthMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string NumberingMasterValue {
            get {
                return ((string)(this["NumberingMasterValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ヘッダー桁数")]
        public string MunicipalCodeLengthLabelName {
            get {
                return ((string)(this["MunicipalCodeLengthLabelName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("拠点コード桁数")]
        public string BranchOfficeLengthLabelName {
            get {
                return ((string)(this["BranchOfficeLengthLabelName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("印鑑登録番号桁数")]
        public string SealRegistrationLengthLabelName {
            get {
                return ((string)(this["SealRegistrationLengthLabelName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ヘッダー")]
        public string MunicipalCodeLabelName {
            get {
                return ((string)(this["MunicipalCodeLabelName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("拠点コード")]
        public string BranchOfficeLabelName {
            get {
                return ((string)(this["BranchOfficeLabelName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("印鑑登録番号 初期値")]
        public string MunicipalCodeName {
            get {
                return ((string)(this["MunicipalCodeName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public decimal BranchOfficeLengthValue {
            get {
                return ((decimal)(this["BranchOfficeLengthValue"]));
            }
            set {
                this["BranchOfficeLengthValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal MunicipalCodeLengthValue {
            get {
                return ((decimal)(this["MunicipalCodeLengthValue"]));
            }
            set {
                this["MunicipalCodeLengthValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public decimal SealRegistrationLengthValue {
            get {
                return ((decimal)(this["SealRegistrationLengthValue"]));
            }
            set {
                this["SealRegistrationLengthValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z99999")]
        public string MunicipalCodeValue {
            get {
                return ((string)(this["MunicipalCodeValue"]));
            }
            set {
                this["MunicipalCodeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99")]
        public string BranchOfficeValue {
            get {
                return ((string)(this["BranchOfficeValue"]));
            }
            set {
                this["BranchOfficeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public char BranchOfficeLeadingCharacter {
            get {
                return ((char)(this["BranchOfficeLeadingCharacter"]));
            }
            set {
                this["BranchOfficeLeadingCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public char MunicipalCodeLeadingCharacter {
            get {
                return ((char)(this["MunicipalCodeLeadingCharacter"]));
            }
            set {
                this["MunicipalCodeLeadingCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public char SealRegistrationLeadingCharacter {
            get {
                return ((char)(this["SealRegistrationLeadingCharacter"]));
            }
            set {
                this["SealRegistrationLeadingCharacter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SealRegistrationValue {
            get {
                return ((string)(this["SealRegistrationValue"]));
            }
            set {
                this["SealRegistrationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BranchOfficeZeroSuppress {
            get {
                return ((bool)(this["BranchOfficeZeroSuppress"]));
            }
            set {
                this["BranchOfficeZeroSuppress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MunicipalCodeZeroSuppress {
            get {
                return ((bool)(this["MunicipalCodeZeroSuppress"]));
            }
            set {
                this["MunicipalCodeZeroSuppress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SealRegistrationZeroSuppress {
            get {
                return ((bool)(this["SealRegistrationZeroSuppress"]));
            }
            set {
                this["SealRegistrationZeroSuppress"] = value;
            }
        }
    }
}
